name: Bug Report
description: Report a bug to help us improve Shizuku+
labels: [bug]
body:
  - type: checkboxes
    id: check
    attributes:
      label: Before reporting
      options:
        - label: I read the [wiki](https://github.com/thejaustin/ShizukuPlus/wiki#troubleshooting) and followed all relevant troubleshooting steps
          required: true
        - label: I searched through all [issues](https://github.com/thejaustin/ShizukuPlus/issues) and confirmed that this is a new bug
          required: true
  - type: input
    id: version
    attributes:
      label: Shizuku version
      description: What version of Shizuku are you using? (e.g., 13.5.4.r1000)
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Device and Android version
      description: What device and Android version are you using? (e.g., Pixel 7, Android 13)
    validations:
      required: true
  - type: textarea
    id: bug_description
    attributes:
      label: Bug description
      description: Please describe the bug clearly.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Please provide clear steps to reproduce the bug.
    validations:
      required: true
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the bug report here.
