name: Feature Request
description: Suggest a feature or improvement for Shizuku+
labels: [enhancement]
body:
  - type: checkboxes
    id: check
    attributes:
      label: Before suggesting
      options:
        - label: I searched through all [open/closed issues](https://github.com/thejaustin/ShizukuPlus/issues) and confirmed that this is a new feature request
          required: true
  - type: textarea
    id: feature_description
    attributes:
      label: Feature description
      description: Please describe the feature you would like to see clearly.
    validations:
      required: true
  - type: textarea
    id: feature_reason
    attributes:
      label: Why do you want this feature?
      description: Please provide a clear explanation for why you would like to see this feature.
    validations:
      required: true
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
